apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-groceries-api
  labels:
    app: go-groceries-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-groceries-api
  template:
    metadata:
      labels:
        app: go-groceries-api
    spec:
      containers:
      - name: go-groceries-api
        image: hokkungleo/go-groceries:v1
        command: ["/script/entrypoint.sh"]
        args: ["internal-api"]
        ports:
        - containerPort: 8080
