  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: go-groceries-api
  spec:
    rules:
      - host: groceries-api.leo.com
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: go-groceries-api
                  port:
                    number: 8080
